swagger: "2.0"
info:
  version: "0"
  title: Webwallet API
host: localhost
basePath: /
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
  
paths:
  /address:
    x-swagger-router-controller: endpoints
    post:
      description: Creates a new wallet address.
      operationId: address.post
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/address:post:success"
        default:
          description: Error
          schema:
            $ref: "#/definitions/address:post:error"
  
  /currency:
    x-swagger-router-controller: endpoints
    post:
      description: Creates a new currency unit.
      operationId: currency.post
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/currency:post:success"
        default:
          description: Error
          schema:
            $ref: "#/definitions/currency:post:error"
            
  /transaction:
    x-swagger-router-controller: endpoints
    post:
      description: Creates a new transaction request.
      operationId: transaction.post
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/transaction:post:success"
        default:
          description: Error
          schema:
            $ref: "#/definitions/transaction:post:error"          

definitions:
  address:post:success:
    required:
      - properties
      - entities
      - actions
      - links
    properties:
      properties:
        type: object
      entities:
        type: array
        items:
          type: object
      actions:
        type: array
        items:
          type: object
      links:
        type: array
        items:
          type: object
        
  currency:post:success:
    required:
      - properties
      - entities
      - actions
      - links
    properties:
      properties:
        type: object
      entities:
        type: array
        items:
          type: object
      actions:
        type: array
        items:
          type: object
      links:
        type: array
        items:
          type: object

  transaction:post:success:
    required:
      - properties
      - entities
      - actions
      - links
    properties:
      properties:
        type: object
      entities:
        type: array
        items:
          type: object
      actions:
        type: array
        items:
          type: object
      links:
        type: array  
        items:
          type: object  
    
  address:post:error:
    required:
      - message
    properties:
      message:
        type: string
  currency:post:error:
    required:
      - message
    properties:
      message:
        type: string
  transaction:post:error:
    required:
      - message
    properties:
      message:
        type: string
